### ISSUE TITLE
Unable to reproduce example in SWGA documentation: Number of remaining primers: 0

### ISSUE THREAD

**Issue by Rohit-Satyam** [songlab-cal/soapswga#17]
Dear @yss1 @janedwivedi 

I tried running new SWGA on your example set and it appears to be running without error. However, I see that no primer is being produced:

```bash
$ soapswga step1 -j $PWD/examples/plasmid_example/params.json -v VERBOSE
======================================================================================================
Parameters:
json_file: /data/swga2/swga2/examples/plasmid_example/params.json
data_dir: /data/swga2/swga2/examples/plasmid_example/
src_dir: /data/swga2/swga2/src/
min_fg_freq: 1e-05
max_bg_freq: 5e-06
min_tm: 15
max_tm: 45
max_gini: 0.6
max_primer: 500
min_amp_pred: 10
cpus: 16
max_dimer_bp: 3
max_self_dimer_bp: 4
fg_genomes: ['/data/swga2/swga2/examples/plasmid_example/pcDNA.fasta']
bg_genomes: ['/data/swga2/swga2/examples/plasmid_example/pLTR.fasta']
fg_prefixes: ['/data/swga2/swga2/examples/plasmid_example/kmer_files/pcDNA']
bg_prefixes: ['/data/swga2/swga2/examples/plasmid_example/kmer_files/pLTR']
mismatch_penalty: 4
verbose: VERBOSE
drop_iterations: 4
iterations: 8
top_set_count: 10
retries: 5
max_sets: 5
selection_metric: deterministic
fg_circular: True
bg_circular: False
fg_seq_lengths: [6157]
bg_seq_lengths: [6258]
======================================================================================================
Running jellyfish for foreground...
Running jellyfish for background...
Done running jellyfish

soapswga step2 -j $PWD/examples/plasmid_example/params.json
======================================================================================================
Parameters:
json_file: /data/swga2/swga2/examples/plasmid_example/params.json
data_dir: /data/swga2/swga2/examples/plasmid_example/
src_dir: /data/swga2/swga2/src/
min_fg_freq: 1e-05
max_bg_freq: 5e-06
min_tm: 15
max_tm: 45
max_gini: 0.6
max_primer: 500
min_amp_pred: 10
cpus: 16
max_dimer_bp: 3
max_self_dimer_bp: 4
fg_genomes: ['/data/swga2/swga2/examples/plasmid_example/pcDNA.fasta']
bg_genomes: ['/data/swga2/swga2/examples/plasmid_example/pLTR.fasta']
fg_prefixes: ['/data/swga2/swga2/examples/plasmid_example/kmer_files/pcDNA']
bg_prefixes: ['/data/swga2/swga2/examples/plasmid_example/kmer_files/pLTR']
mismatch_penalty: 4
verbose: VERBOSE
drop_iterations: 4
iterations: 8
top_set_count: 10
retries: 5
max_sets: 5
selection_metric: deterministic
fg_circular: True
bg_circular: False
fg_seq_lengths: [6157]
bg_seq_lengths: [6258]
======================================================================================================
Computing foreground and background rates...
Filtered 0 number of primers based on foreground/background rate.
Empty DataFrame
Columns: [primer, fg_count, bg_count, fg_bool, bg_bool]
Index: []
Computing Gini index...
Filtered 0 number of primers based on gini rate.
Number of remaining primers: 0

soapswga step3 -j $PWD/examples/plasmid_example/params.json
======================================================================================================
Parameters:
json_file: /data/swga2/swga2/examples/plasmid_example/params.json
data_dir: /data/swga2/swga2/examples/plasmid_example/
src_dir: /data/swga2/swga2/src/
min_fg_freq: 1e-05
max_bg_freq: 5e-06
min_tm: 15
max_tm: 45
max_gini: 0.6
max_primer: 500
min_amp_pred: 10
cpus: 16
max_dimer_bp: 3
max_self_dimer_bp: 4
fg_genomes: ['/data/swga2/swga2/examples/plasmid_example/pcDNA.fasta']
bg_genomes: ['/data/swga2/swga2/examples/plasmid_example/pLTR.fasta']
fg_prefixes: ['/data/swga2/swga2/examples/plasmid_example/kmer_files/pcDNA']
bg_prefixes: ['/data/swga2/swga2/examples/plasmid_example/kmer_files/pLTR']
mismatch_penalty: 4
verbose: VERBOSE
drop_iterations: 4
iterations: 8
top_set_count: 10
retries: 5
max_sets: 5
selection_metric: deterministic
fg_circular: True
bg_circular: False
fg_seq_lengths: [6157]
bg_seq_lengths: [6258]
======================================================================================================
Number of primers beginning of step 3: 0
Computing random forest features...
feature matrix was none
delta G matrix was none
Done with fg
Computing amplification efficacy...
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/swga/bin/soapswga", line 8, in <module>
    sys.exit(main())
  File "/home/subudhak/miniconda3/envs/swga/lib/python3.7/site-packages/src/pipeline.py", line 122, in main
    step3()
  File "/home/subudhak/miniconda3/envs/swga/lib/python3.7/site-packages/src/pipeline.py", line 226, in step3
    results = src.rf_preprocessing.predict_new_primers(df_pred)
  File "/home/subudhak/miniconda3/envs/swga/lib/python3.7/site-packages/src/rf_preprocessing.py", line 242, in predict_new_primers
    y_pred = clf.predict(X_test)
  File "/home/subudhak/miniconda3/envs/swga/lib/python3.7/site-packages/sklearn/ensemble/forest.py", line 693, in predict
    X = self._validate_X_predict(X)
  File "/home/subudhak/miniconda3/envs/swga/lib/python3.7/site-packages/sklearn/ensemble/forest.py", line 359, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/home/subudhak/miniconda3/envs/swga/lib/python3.7/site-packages/sklearn/tree/tree.py", line 391, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "/home/subudhak/miniconda3/envs/swga/lib/python3.7/site-packages/sklearn/utils/validation.py", line 550, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 53)) while a minimum of 1 is required.

```

I don't understand why no. of remaining primers are zero? All the kmer files are empty
```
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pcDNA_10mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pcDNA_11mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pcDNA_12mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pcDNA_6mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pcDNA_7mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pcDNA_8mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pcDNA_9mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pLTR_10mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pLTR_11mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pLTR_12mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pLTR_6mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pLTR_7mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pLTR_8mer_all.txt
-rw-rw-r-- 1 subudhak g-subudhak    0 Aug 20 13:53 pLTR_9mer_all.txt
```
I installed the swga as described [here](https://github.com/songlab-cal/swga2/issues/16#issuecomment-2298968753)

**Comment by Rohit-Satyam** [comment]
Issue resolved by installing `jellyfish 2.3.1` from mamba using `mamba install -c bioconda kmer-jellyfish`. Please update README for the installation instructions since Jellyfish 1.11 gives the following error if I follow the URL you gave for its installation: 
```
terminate called after throwing an instance of 'mapped_file::ErrorMMap'
  what():  Can't open file '/data/swga2/swga2/examples/plasmid_example/kmer_files/pcDNA_6mer_all.jf': No such file or directory
sh: line 1: 298384 Aborted                 (core dumped) jellyfish dump -c /data/swga2/swga2/examples/plasmid_example/kmer_files/pcDNA_6mer_all.jf > /data/swga2/swga2/examples/plasmid_example/kmer_files/pcDNA_6mer_all.txt
```
