### ISSUE TITLE
Installation fails for both python 3.10 and 3.8

### ISSUE THREAD

**Issue by Rohit-Satyam** [songlab-cal/soapswga#5]
Hi

I was trying to install new SWGA and I get the following error with **Python 3.8**

```
Building wheel for et-xmlfile (setup.py) ... done
  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-py3-none-any.whl size=8899 sha256=82b23816e61ff5161b9d13bbabd3bc90eb5b3d2535fd39221078318bd81661e3
  Stored in directory: /home/subudhak/.cache/pip/wheels/6e/df/38/abda47b884e3e25f9f9b6430e5ce44c47670758a50c0c51759
  Building wheel for melt (setup.py) ... done
  Created wheel for melt: filename=melt-1.0.3-py3-none-any.whl size=4704 sha256=128601be8ff3cbce6e74ccd9131e4106167d5b18a89c2fcd8b05ee745a9437f3
  Stored in directory: /home/subudhak/.cache/pip/wheels/b1/8e/2e/2de52488df076d89280917cc9483952373f7d16bc7fd72fb59
  Building wheel for openpyxl (setup.py) ... done
  Created wheel for openpyxl: filename=openpyxl-3.0.2-py2.py3-none-any.whl size=241183 sha256=46c2a52f56098785f4355514997f8ac0908620c062ada62494ec7e98937ea861
  Stored in directory: /home/subudhak/.cache/pip/wheels/0e/0e/96/7b5d42c07853d2126e429e28af5baaf01b3ef23c98498a3c98
  Building wheel for scikit-learn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Partial import of sklearn during the build process.
      /tmp/pip-install-bxmd0295/scikit-learn_6c37d3a3a9704e6396663cf0817a1ec3/setup.py:122: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.command.build_ext import build_ext  # noqa
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bxmd0295/scikit-learn_6c37d3a3a9704e6396663cf0817a1ec3/setup.py", line 290, in <module>
          setup_package()
        File "/tmp/pip-install-bxmd0295/scikit-learn_6c37d3a3a9704e6396663cf0817a1ec3/setup.py", line 286, in setup_package
          setup(**metadata)
        File "/home/subudhak/.local/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
          config = configuration()
        File "/tmp/pip-install-bxmd0295/scikit-learn_6c37d3a3a9704e6396663cf0817a1ec3/setup.py", line 174, in configuration
          config.add_subpackage('sklearn')
        File "/home/subudhak/.local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1050, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/home/subudhak/.local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/home/subudhak/.local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 958, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "sklearn/setup.py", line 62, in configuration
          config.add_subpackage('utils')
        File "/home/subudhak/.local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1050, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/home/subudhak/.local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/home/subudhak/.local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 958, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "sklearn/utils/setup.py", line 8, in configuration
          from Cython import Tempita
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Successfully built et-xmlfile melt openpyxl
Failed to build scikit-learn
Installing collected packages: sortedcontainers, pytz, melt, joblib, jdcal, et-xmlfile, six, openpyxl, numpy, scipy, python-dateutil, scikit-learn, pandas
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.2
    Uninstalling numpy-1.23.2:
      Successfully uninstalled numpy-1.23.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.1.2
    Uninstalling scikit-learn-1.1.2:
      Successfully uninstalled scikit-learn-1.1.2
  Running setup.py install for scikit-learn ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for scikit-learn did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bxmd0295/scikit-learn_6c37d3a3a9704e6396663cf0817a1ec3/setup.py", line 290, in <module>
          setup_package()
        File "/tmp/pip-install-bxmd0295/scikit-learn_6c37d3a3a9704e6396663cf0817a1ec3/setup.py", line 286, in setup_package
          setup(**metadata)
        File "/home/subudhak/miniconda3/envs/swga/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
          config = configuration()
        File "/tmp/pip-install-bxmd0295/scikit-learn_6c37d3a3a9704e6396663cf0817a1ec3/setup.py", line 174, in configuration
          config.add_subpackage('sklearn')
        File "/home/subudhak/miniconda3/envs/swga/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/home/subudhak/miniconda3/envs/swga/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/home/subudhak/miniconda3/envs/swga/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "sklearn/setup.py", line 62, in configuration
          config.add_subpackage('utils')
        File "/home/subudhak/miniconda3/envs/swga/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "/home/subudhak/miniconda3/envs/swga/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "/home/subudhak/miniconda3/envs/swga/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "sklearn/utils/setup.py", line 8, in configuration
          from Cython import Tempita
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of scikit-learn
  Moving to /home/subudhak/.local/lib/python3.8/site-packages/scikit_learn-1.1.2.dist-info/
   from /home/subudhak/.local/lib/python3.8/site-packages/~cikit_learn-1.1.2.dist-info
  Moving to /home/subudhak/.local/lib/python3.8/site-packages/scikit_learn.libs/
   from /home/subudhak/.local/lib/python3.8/site-packages/~cikit_learn.libs
  Moving to /home/subudhak/.local/lib/python3.8/site-packages/sklearn/
   from /home/subudhak/.local/lib/python3.8/site-packages/~klearn
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> scikit-learn

note: This is an issue with the package mentioned above, not pip.
```

**Comment by Milind-Mutnale** [comment]
@Rohit-Satyam 

Try to install via conda       https://anaconda.org/janedwivedi/swga2

see the description for the installation on that page.

**Comment by janeyubear** [comment]
Hi there, it seems you are missing Cython? Does `pip install Cython` do the trick?

**Comment by Rohit-Satyam** [comment]
I finally took help of my IT team and they installed it somehow. So it's working for now. I don't know what exactly they did.

**Comment by TGeneralovic** [comment]
I can confirm `pip install Cython` does the trick. see below for output.

I also ran into the same issue as opened in this ticket, after a fresh install I recieved:
```
(python3.8) [tng23@login-e-9 swga2-master]$ pip install -r requirements.txt
Collecting et-xmlfile==1.0.1
  Using cached et_xmlfile-1.0.1.tar.gz (8.4 kB)
  Preparing metadata (setup.py) ... done
Collecting h5py==2.10.0
  Using cached h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
Collecting jdcal==1.4.1
  Using cached jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)
Collecting joblib==0.14.1
  Using cached joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Collecting melt==1.0.3
  Using cached melt-1.0.3.tar.gz (4.3 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.18.0
  Using cached numpy-1.18.0-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
Collecting openpyxl==3.0.2
  Using cached openpyxl-3.0.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... done
Collecting pandas==1.0.0
  Using cached pandas-1.0.0-cp38-cp38-manylinux1_x86_64.whl (9.9 MB)
Collecting python-dateutil==2.8.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz==2019.3
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Requirement already satisfied: scipy==1.4.1 in /usr/local/software/master/python/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (1.4.1)
Collecting scikit-learn==0.21.3
  Using cached scikit-learn-0.21.3.tar.gz (12.2 MB)
  Preparing metadata (setup.py) ... done
Collecting six==1.13.0
  Using cached six-1.13.0-py2.py3-none-any.whl (10 kB)
Collecting sortedcontainers==2.1.0
  Using cached sortedcontainers-2.1.0-py2.py3-none-any.whl (28 kB)
Building wheels for collected packages: et-xmlfile, melt, openpyxl, scikit-learn
  Building wheel for et-xmlfile (setup.py) ... done
  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-py3-none-any.whl size=8915 sha256=40d81987c8867548dc31e027d9d43de22df152dbde4449a6cb6d02f794a85c29
  Stored in directory: /home/tng23/.cache/pip/wheels/6e/df/38/abda47b884e3e25f9f9b6430e5ce44c47670758a50c0c51759
  Building wheel for melt (setup.py) ... done
  Created wheel for melt: filename=melt-1.0.3-py3-none-any.whl size=4721 sha256=db4ac9fbcaf4cc6ed195bca8d9912bb6988bfa796c416595200fd306f66f75cc
  Stored in directory: /home/tng23/.cache/pip/wheels/b1/8e/2e/2de52488df076d89280917cc9483952373f7d16bc7fd72fb59
  Building wheel for openpyxl (setup.py) ... done
  Created wheel for openpyxl: filename=openpyxl-3.0.2-py2.py3-none-any.whl size=241197 sha256=47316f7ae9a7d664f26501b38e414965b02ca9bb230782a2651c4c0d30b44b40
  Stored in directory: /home/tng23/.cache/pip/wheels/0e/0e/96/7b5d42c07853d2126e429e28af5baaf01b3ef23c98498a3c98
  Building wheel for scikit-learn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /rds/user/tng23/hpc-work/virtualenvs/python3.8/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-38c_x8m8
       cwd: /tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/
  Complete output (28 lines):
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py", line 290, in <module>
      setup_package()
    File "/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py", line 286, in setup_package
      setup(**metadata)
    File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
      config = configuration()
    File "/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py", line 174, in configuration
      config.add_subpackage('sklearn')
    File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sklearn/setup.py", line 62, in configuration
      config.add_subpackage('utils')
    File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/usr/local/software/master/python/3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sklearn/utils/setup.py", line 8, in configuration
      from Cython import Tempita
  ModuleNotFoundError: No module named 'Cython'
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Successfully built et-xmlfile melt openpyxl
Failed to build scikit-learn
Installing collected packages: six, pytz, python-dateutil, numpy, joblib, jdcal, et-xmlfile, sortedcontainers, scikit-learn, pandas, openpyxl, melt, h5py
  Attempting uninstall: six
    Found existing installation: six 1.14.0
    Not uninstalling six at /usr/local/software/master/python/3.8/lib/python3.8/site-packages, outside environment /rds/user/tng23/hpc-work/virtualenvs/python3.8
    Can't uninstall 'six'. No files were found to uninstall.
  Attempting uninstall: pytz
    Found existing installation: pytz 2021.3
    Uninstalling pytz-2021.3:
      Successfully uninstalled pytz-2021.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.2
    Uninstalling python-dateutil-2.8.2:
      Successfully uninstalled python-dateutil-2.8.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.3
    Not uninstalling numpy at /usr/local/software/master/python/3.8/lib/python3.8/site-packages, outside environment /rds/user/tng23/hpc-work/virtualenvs/python3.8
    Can't uninstall 'numpy'. No files were found to uninstall.
    Running setup.py install for scikit-learn ... error
    ERROR: Command errored out with exit status 1:
     command: /rds/user/tng23/hpc-work/virtualenvs/python3.8/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-26qttk8s/install-record.txt --single-version-externally-managed --compile --install-headers /rds/user/tng23/hpc-work/virtualenvs/python3.8/include/site/python3.8/scikit-learn
         cwd: /tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/
    Complete output (28 lines):
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py", line 290, in <module>
        setup_package()
      File "/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py", line 286, in setup_package
        setup(**metadata)
      File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py", line 174, in configuration
        config.add_subpackage('sklearn')
      File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/setup.py", line 62, in configuration
        config.add_subpackage('utils')
      File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/utils/setup.py", line 8, in configuration
        from Cython import Tempita
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /rds/user/tng23/hpc-work/virtualenvs/python3.8/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oecym6by/scikit-learn_caf2923eba5d4c92a975476514ee6f44/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-26qttk8s/install-record.txt --single-version-externally-managed --compile --install-headers /rds/user/tng23/hpc-work/virtualenvs/python3.8/include/site/python3.8/scikit-learn Check the logs for full command output.
```
After installing Cython:
`(python3.8) [tng23@login-e-9 swga2-master]$ pip install Cython
Collecting Cython
  Downloading Cython-0.29.32-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 9.3 MB/s
Installing collected packages: Cython
Successfully installed Cython-0.29.32
WARNING: You are using pip version 21.3; however, version 22.3.1 is available.
You should consider upgrading via the '/rds/user/tng23/hpc-work/virtualenvs/python3.8/bin/python3.8 -m pip install --upgrade pip' command.
(python3.8) [tng23@login-e-9 swga2-master]$ pip install -r requirements.txt
Requirement already satisfied: et-xmlfile==1.0.1 in /rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.0.1)
Collecting h5py==2.10.0
  Using cached h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
Requirement already satisfied: jdcal==1.4.1 in /rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (1.4.1)
Requirement already satisfied: joblib==0.14.1 in /rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.14.1)
Collecting melt==1.0.3
  Using cached melt-1.0.3-py3-none-any.whl
Requirement already satisfied: numpy==1.18.0 in /rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.18.0)
Collecting openpyxl==3.0.2
  Using cached openpyxl-3.0.2-py2.py3-none-any.whl
Collecting pandas==1.0.0
  Using cached pandas-1.0.0-cp38-cp38-manylinux1_x86_64.whl (9.9 MB)
Requirement already satisfied: python-dateutil==2.8.1 in /rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (2.8.1)
Requirement already satisfied: pytz==2019.3 in /rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (2019.3)
Requirement already satisfied: scipy==1.4.1 in /usr/local/software/master/python/3.8/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (1.4.1)
Collecting scikit-learn==0.21.3
  Using cached scikit-learn-0.21.3.tar.gz (12.2 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six==1.13.0 in /rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (1.13.0)
Requirement already satisfied: sortedcontainers==2.1.0 in /rds/user/tng23/hpc-work/virtualenvs/python3.8/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (2.1.0)
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (setup.py) ... done
  Created wheel for scikit-learn: filename=scikit_learn-0.21.3-cp38-cp38-linux_x86_64.whl size=18401311 sha256=9452ba1cb8393180778db58ecbb5edfb49f03e950a83e0d59d2d9f3341082469
  Stored in directory: /home/tng23/.cache/pip/wheels/50/a7/f7/d987583cd3b9bec683f517206b66b259dfb9b67ee043ce7ac3
Successfully built scikit-learn
Installing collected packages: scikit-learn, pandas, openpyxl, melt, h5py
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.3
    Uninstalling pandas-1.3.3:
      Successfully uninstalled pandas-1.3.3
Successfully installed h5py-2.10.0 melt-1.0.3 openpyxl-3.0.2 pandas-1.0.0 scikit-learn-0.21.3`

I re-ran:
`pip install -r requirements.txt`

I sucsessfully got the requiremnets installed:

`(python3.8) [tng23@login-e-9 swga2-master]$ pip install .
Processing /rds/user/tng23/hpc-work/project_AH_SWJ/swga2-master
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: SOAPswga
  Building wheel for SOAPswga (setup.py) ... done
  Created wheel for SOAPswga: filename=SOAPswga-0.0.1-py3-none-any.whl size=49748 sha256=9dc7c98ac232d879f97034c164b75f2ab57b68a992c300e455b697092ae1171d
  Stored in directory: /home/tng23/.cache/pip/wheels/89/cd/d5/d1c2194c474ff0d6b699adfc3eb1f56742993c0b353fc3ffc7
Successfully built SOAPswga
Installing collected packages: SOAPswga
Successfully installed SOAPswga-0.0.1
`
